In [110]:
using Random
using LinearAlgebra
using Test

In [111]:
m = 8; # number of eulerian points
n = 4; # number of lagrangian points

In [120]:
L = rand(m,m)
H = rand(m,n)
E = transpose(H)
Ob = rand(n)
ObT = transpose(Ob)
ψ = rand(m)
f = rand(n)
w = rand(m)
ψb = rand(n)
Γ₀ = rand(1)[1]

0.7101875171994803

In [121]:
rhs = [-w; ψb; Γ₀]

13-element Array{Float64,1}:
 -0.48164389261823604 
 -0.961996197526332   
 -0.02776373964223766 
 -0.11012024689783839 
 -0.5266257011257227  
 -0.31272045816148664 
 -0.6454635481971871  
 -0.004470568423669663
  0.516821143130016   
  0.9832645937117364  
  0.9808537467207981  
  0.9583119038103773  
  0.7101875171994803  

In [122]:
sys = [L H zeros(m,1); E zeros(n,n) Ob; zeros(1,m) ObT zeros(1,1)]

13×13 Array{Float64,2}:
 0.57974    0.121081   0.942555   …  0.994905   0.395382   0.0     
 0.151898   0.0832124  0.413634      0.983944   0.776745   0.0     
 0.969724   0.430727   0.576185      0.416405   0.0517104  0.0     
 0.354825   0.677046   0.321422      0.0505648  0.0589594  0.0     
 0.967443   0.230301   0.100671      0.0947762  0.913583   0.0     
 0.110904   0.0165742  0.252508   …  0.653836   0.0854262  0.0     
 0.0258994  0.342419   0.587425      0.522501   0.858554   0.0     
 0.657777   0.360769   0.293889      0.151247   0.750362   0.0     
 0.297403   0.817389   0.71159       0.0        0.0        0.684626
 0.994211   0.0366242  0.511697      0.0        0.0        0.221126
 0.994905   0.983944   0.416405   …  0.0        0.0        0.330385
 0.395382   0.776745   0.0517104     0.0        0.0        0.180784
 0.0        0.0        0.0           0.330385   0.180784   0.0     

In [123]:
x = sys\rhs

13-element Array{Float64,1}:
 -1.0713090591345231 
  4.751687562942738  
  7.639539647407677  
 -2.8905430346301455 
  8.306853112202706  
 -2.7674979716163732 
 -9.889845918361354  
 -2.52098342226877   
  1.1524697485796591 
  2.283554662494075  
 -2.0364443844089624 
  0.49249049210713813
  2.7460899569474106 

Eldredge formulas

In [124]:
S = -E*inv(L)*H
S₀ = ObT*(S\Ob)
T = S - Ob*ObT/S₀;

ψ₀ = -1/S₀*(Γ₀ - ObT*(S\ψb));
display(ψ₀)
f = S\(T*(S\ψb) .+ Γ₀*Ob/S₀);
display(f)
ψ .= -(L\(H*f)); # Total streamfunction
display(ψ)

2.0224286403799803

4-element Array{Float64,1}:
  0.7314910650868407
  2.2794281737143796
 -1.3736277521915408
  0.880471561195129 

8-element Array{Float64,1}:
  -1.738564298100444 
   5.498857798582059 
   8.865289740948477 
  -3.301895666856788 
   9.874928550548127 
  -2.0268687250321147
 -11.629392270512358 
  -2.8237529720971315

In [125]:
@test x ≈ [ψ; f; ψ₀] atol=0.01

Test Failed at In[125]:1
  Expression: ≈(x, [ψ; f; ψ₀], atol=0.01)
   Evaluated: [-1.07131, 4.75169, 7.63954, -2.89054, 8.30685, -2.7675, -9.88985, -2.52098, 1.15247, 2.28355, -2.03644, 0.49249, 2.74609] ≈ [-1.73856, 5.49886, 8.86529, -3.3019, 9.87493, -2.02687, -11.6294, -2.82375, 0.731491, 2.27943, -1.37363, 0.880472, 2.02243] (atol=0.01) 


Test.FallbackTestSetException: There was an error during testing

Newly derived formulas

In [128]:
S = -E*inv(L)*H
S₀ = ObT*(S\Ob)
T = S - Ob*ObT/S₀;

ψ₀ = -1/S₀*(Γ₀ .- ObT*(S\(E*(L\w).+ψb)));
display(ψ₀)
f = S\(T*(S\(E*(L\w).+ψb)) .+ Γ₀*Ob/S₀);
display(f)
ψ = -(L\(H*f.+w));
display(ψ)

2.746089956947396

4-element Array{Float64,1}:
  1.1524697485796598
  2.2835546624940615
 -2.036444384408952 
  0.4924904921071318

8-element Array{Float64,1}:
 -1.071309059134515 
  4.751687562942726 
  7.63953964740766  
 -2.89054303463015  
  8.306853112202685 
 -2.7674979716163555
 -9.889845918361326 
 -2.5209834222687664

In [129]:
@test x ≈ [ψ; f; ψ₀] atol=0.01

Test Passed